env:
  global:
    - CC_TEST_REPORTER_ID=<%= Rails.application.credentials[:code_climate][:reporter_id] %>
language: ruby
rvm:
  - 2.5.3
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec --format documentation --color
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
services:
  - postgresql
